-- GetHotel Database Schema
-- Optimized for MilesWeb Shared Hosting

SET FOREIGN_KEY_CHECKS = 0;

-- Drop tables if they exist
DROP TABLE IF EXISTS `RevenueLog`;
DROP TABLE IF EXISTS `Enquiry`;
DROP TABLE IF EXISTS `Newsletter`;
DROP TABLE IF EXISTS `PartnerProfile`;
DROP TABLE IF EXISTS `DailyRate`;
DROP TABLE IF EXISTS `Review`;
DROP TABLE IF EXISTS `Booking`;
DROP TABLE IF EXISTS `Room`;
DROP TABLE IF EXISTS `Hotel`;
DROP TABLE IF EXISTS `User`;

-- Create User Table
CREATE TABLE `User` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(191) NOT NULL,
  `email` VARCHAR(191) NOT NULL UNIQUE,
  `password` VARCHAR(191) NOT NULL,
  `role` ENUM('USER', 'PARTNER', 'SUPER_ADMIN') NOT NULL DEFAULT 'USER',
  `profileImage` VARCHAR(191) NULL,
  `isVerified` TINYINT(1) NOT NULL DEFAULT 0,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Create Partner Profile Table
CREATE TABLE `PartnerProfile` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `userId` INT NOT NULL UNIQUE,
  `businessName` VARCHAR(191) NOT NULL,
  `gstNumber` VARCHAR(191) NULL,
  `panNumber` VARCHAR(191) NULL,
  `address` TEXT NULL,
  `phone` VARCHAR(191) NULL,
  `bankName` VARCHAR(191) NULL,
  `accountNumber` VARCHAR(191) NULL,
  `ifscCode` VARCHAR(191) NULL,
  `status` ENUM('PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
  CONSTRAINT `PartnerProfile_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User` (`id`) ON DELETE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Create Hotel Table
CREATE TABLE `Hotel` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(191) NOT NULL,
  `tagline` VARCHAR(191) NULL,
  `description` TEXT NOT NULL,
  `city` VARCHAR(191) NOT NULL,
  `address` TEXT NOT NULL,
  `pricePerNight` DOUBLE NOT NULL,
  `starRating` INT NOT NULL DEFAULT 3,
  `guestRating` DOUBLE NOT NULL DEFAULT 0,
  `reviewCount` INT NOT NULL DEFAULT 0,
  `thumbnail` VARCHAR(191) NULL,
  `images` JSON NULL,
  `amenities` JSON NULL,
  `isFeatured` TINYINT(1) NOT NULL DEFAULT 0,
  `isTrending` TINYINT(1) NOT NULL DEFAULT 0,
  `status` ENUM('DRAFT', 'PUBLISHED', 'SUSPENDED') NOT NULL DEFAULT 'DRAFT',
  `userId` INT NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  CONSTRAINT `Hotel_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Create Room Table
CREATE TABLE `Room` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(191) NOT NULL,
  `bedConfiguration` VARCHAR(191) NULL,
  `sizeM2` INT NULL,
  `maxOccupancy` INT NOT NULL DEFAULT 2,
  `pricePerNight` DOUBLE NOT NULL,
  `amenities` JSON NULL,
  `images` JSON NULL,
  `totalRooms` INT NOT NULL DEFAULT 1,
  `hotelId` INT NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  CONSTRAINT `Room_hotelId_fkey` FOREIGN KEY (`hotelId`) REFERENCES `Hotel` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Create Booking Table
CREATE TABLE `Booking` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `userId` INT NOT NULL,
  `hotelId` INT NOT NULL,
  `roomId` INT NOT NULL,
  `checkIn` DATETIME(3) NOT NULL,
  `checkOut` DATETIME(3) NOT NULL,
  `totalPrice` DOUBLE NOT NULL,
  `totalGuests` INT NOT NULL,
  `status` ENUM('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED') NOT NULL DEFAULT 'PENDING',
  `paymentStatus` ENUM('UNPAID', 'PARTIAL', 'PAID', 'REFUNDED') NOT NULL DEFAULT 'UNPAID',
  `amountPaid` DOUBLE NOT NULL DEFAULT 0,
  `razorpayOrderId` VARCHAR(191) NULL UNIQUE,
  `razorpayPaymentId` VARCHAR(191) NULL UNIQUE,
  `customerName` VARCHAR(191) NOT NULL,
  `customerEmail` VARCHAR(191) NOT NULL,
  `customerPhone` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  CONSTRAINT `Booking_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `Booking_hotelId_fkey` FOREIGN KEY (`hotelId`) REFERENCES `Hotel` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `Booking_roomId_fkey` FOREIGN KEY (`roomId`) REFERENCES `Room` (`id`) ON DELETE RESTRICT
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Create Revenue Log Table (18/82 Split)
CREATE TABLE `RevenueLog` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `bookingId` INT NOT NULL UNIQUE,
  `totalAmount` DOUBLE NOT NULL,
  `adminShare` DOUBLE NOT NULL, -- 18%
  `partnerShare` DOUBLE NOT NULL, -- 82%
  `status` ENUM('PENDING', 'PAID_TO_PARTNER') NOT NULL DEFAULT 'PENDING',
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT `RevenueLog_bookingId_fkey` FOREIGN KEY (`bookingId`) REFERENCES `Booking` (`id`) ON DELETE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Create Enquiry Table
CREATE TABLE `Enquiry` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(191) NOT NULL,
  `email` VARCHAR(191) NOT NULL,
  `phone` VARCHAR(191) NULL,
  `subject` VARCHAR(191) NULL,
  `message` TEXT NOT NULL,
  `status` ENUM('NEW', 'READ', 'RESPONDED') NOT NULL DEFAULT 'NEW',
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Create Newsletter Table
CREATE TABLE `Newsletter` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `email` VARCHAR(191) NOT NULL UNIQUE,
  `isActive` TINYINT(1) NOT NULL DEFAULT 1,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Seed Data
INSERT INTO `User` (`id`, `name`, `email`, `password`, `role`) VALUES
(1, 'Super Admin', 'admin@gethotelstays.com', '$2b$10$WEiMSDOHtXlgNf2TwAuLqO2i4XPOaTIhNTAzR2ghOUN7Zu6F1AsP2', 'SUPER_ADMIN');

SET FOREIGN_KEY_CHECKS = 1;
